export const videoDB = {
    Humour: [
      {
        name: "The agony of trying to unsubscribe",
        speaker: "James Veitch",
        rating: "4.5/5",
        link: "https://youtu.be/KUb0JBOIOAA",
      },
      {
        name: "How I hacked online dating",
        speaker: "Amy Webb",
        rating: "4/5",
        link: "https://youtu.be/d6wG_sAdP0U",
      },
      {
        name: "This is what happens when you reply to spam mail",
        speaker: "James Veitch",
        rating: "4.5/5",
        link: "https://youtu.be/LiLS7U7YIdc",
      },
      {
        name: "The Skill of Humor",
        speaker: "Andrew Tarvin",
        rating: "3.5/5",
        link: "https://www.youtube.com/watch?v=MdZAMSyn_As&t=5s",
      },
      {
        name: "Leading with Laughter: The Power of Humor in Leadership",
        speaker: "Paul Osincup",
        rating: "4/5",
        link: "https://www.youtube.com/watch?v=yhokMZdQ7gs"
      },
      {
        name: "What makes things funny",
        speaker: "Peter McGraw",
        rating: "5/5",
        link: "https://www.youtube.com/watch?v=ysSgG5V-R3U",
      },
      {
        name: "Jokes are my superpower",
        speaker: "Danny Zuker",
        rating: "3/5",
        link: "https://www.youtube.com/watch?v=Ma0psvGe2OI",
      },
      {
        name:"Can Comedy Be Funny Anymore?",
        speaker:"Andrew Schulz",
        rating:"5/5",
        link:"https://www.youtube.com/watch?v=dl2MQq4qO4Y",
      },
      {
        name:"Laughter is Medicine",
        speaker:"Anjelah Johnson",
        rating:"4/5",
        link:"https://www.youtube.com/watch?v=g6TUZm5wzLs",
      },
    ],
    "Mental Health": [
      {
        name: "The puzzle of motivation",
        speaker: "Daniel Pink",
        rating: "4.5/5",
        link: "https://youtu.be/rrkrvAUbU9Y",
      },
      {
        name: "Inside the mind of a master procrastinator",
        speaker: "Tim Urban",
        rating: "5/5",
        link: "https://youtu.be/arj7oStGLkU",
      },
      {
        name: "What They Don't Tell You About Mental Illness",
        speaker: "Elizabeth Medina ",
        rating: "4/5",
        link: "https://www.youtube.com/watch?v=ieXB-BGxYwg",
      },
      {
        name:"Mental health for all, by all",
        speaker:"Vikram Patel",
        rating:"4/5",
        link:"https://www.youtube.com/watch?v=gS-p4Piggy8",    
      },
      {
        name:"How to cope with anxiety",
        speaker:"Olivia Remes",
        rating:"4.5/5",
        link:"https://www.youtube.com/watch?v=WWloIAQpMcQ",
      },
      {
        name:"8 principles to achieve optimum mental health",
        speaker:'Dan Banos',
        rating:"5/5",
        link:"https://www.youtube.com/watch?v=oWjSdwzOA6k",
      },
      {
        name:"Is Social Media Hurting Your Mental Health?",
        speaker:"Bailey Parnell",
        rating:"4.5/5",
        link:"https://www.youtube.com/watch?v=Czg_9C7gw0o",
      },
      {
        name:"Feed Your Mental Health",
        speaker:"Drew Ramsey",
        rating:"3.5/5",
        link:"https://www.youtube.com/watch?v=BbLFsQubdtw",
      },
      {
        name:"Tales from a teenage mental health advocate",
        speaker:"Amanda Southworth",
        rating:"3/5",
        link:"https://www.youtube.com/watch?v=pLOagmZTWmM",
      },
    ],
    "Self Improvement": [
      {
        name: "How great leaders inspire action?",
        speaker: "Simon Sinek",
        rating: "5/5",
        link: "https://youtu.be/qp0HIF3SfI4",
      },
      {
        name: "How to speak so that people want to listen?",
        speaker: "Julian Treasure",
        rating: "4.5/5",
        link: "https://youtu.be/eIho2S0ZahI",
      },
      {
        name: "Your body language may shape who you are",
        speaker: "Amy Cuddy",
        rating: "4/5",
        link: "https://youtu.be/Ks-_Mh1QhMc",
      },
      {
        name:"The Dark Side of Self Improvement",
        speaker:" Suzanne Eder",
        rating:"3.5/5",
        link:"https://www.youtube.com/watch?v=wljRiAofFJ8",
      },
      {
        name:"The key to transforming yourself",
        speaker:"Robert Greene",
        rating:"5/5",
        link:'https://www.youtube.com/watch?v=gLt_yDvdeLQ',
      },
      {
        name:"How to be the best version of yourself",
        speaker:"Raquel Caballero",
        rating:"4.5/4",
        link:"https://www.youtube.com/watch?v=WfuXYk6phMY",
      },
      {
        name:"The skill of self confidence",
        speaker:"Dr. Ivan Joseph",
        rating:"3/5",
        link:"https://www.youtube.com/watch?v=w-HYZv6HzAs",
      },
      {
        name:"Why self help will not change your life",
        speaker:"Marianne Power",
        rating:"4.5/5",
        link:"https://www.youtube.com/watch?v=YWO-NbYmmFg",
      },
      {
        name:"Kaizen at Home - 90 Days to Success",
        speaker:"Mike Morrill",
        rating:"4/5",
        link:"https://www.youtube.com/watch?v=yC3S9e7yl_0",
      },
    ],
  };